### ISSUE TITLE
LSP operations within preview window

### ISSUE THREAD

**Issue by ldelossa** [DNLHC/glance.nvim#19] opened 2022-11-28 14:06 UTC
Hey, 

How often do you expect users to perform LSP operations *within* the preview window? 

A couple issues I've found is:

* Calling "Glance definitions" within the preview window doesn't seem to work. IMO, it should close current Glance window and possibly open a new one with the preview of the symbol within the original preview window. 

* Zindex for Glance should be lower then LSP popups such as "hover"

![image](https://user-images.githubusercontent.com/5642902/204297304-5f4473d0-c4ff-453e-ae4f-f58ffba48881.png)

In the above image, the preview window is covering the hover info for a symbol's hover info within the preview window.

**Comment by DNLHC** [comment] 2022-11-28 14:37
>  IMO, it should close current Glance window and possibly open a new one with the preview of the symbol within the original preview window

Yes, that was the intended behavior, but clearly something went wrong
Thanks for bringing it to my attention, i'll check it out.

> Zindex for Glance should be lower then LSP popups such as "hover"

Good point. I believe zindex should also be configurable by the user.

**Comment by ldelossa** [comment] 2022-11-29 01:32
![image](https://user-images.githubusercontent.com/5642902/204416378-4829188e-339e-4f48-b1b9-dbd994a12264.png)

latest commit works great :+1:

**Comment by nyz93** [comment] 2023-01-17 13:28
Re-calling `Glance` inside the preview doesn't work as expected because the preview is closed here: https://github.com/DNLHC/glance.nvim/blob/611478d2b36beb3c416c92f77e7c116d7bd25ee6/lua/glance/init.lua#L240 before the buffer/position is calculated here: https://github.com/DNLHC/glance.nvim/blob/611478d2b36beb3c416c92f77e7c116d7bd25ee6/lua/glance/init.lua#L141
Making sure that `nvim_get_current_buf` and `make_position_params` is called before closing the preview does fix the issue but it also causes the plugin to just stop working suddenly.

**Comment by DNLHC** [comment] 2023-01-30 18:12
completed in 1ca3ab13fd67a01bcc0c3af953ebcaf1c2ac12d2

**Closed as completed by DNLHC** 2023-01-30 18:12 UTC
