### ISSUE TITLE
Column value outside range

### ISSUE THREAD

**Issue by lvim-tech** [DNLHC/glance.nvim#2] opened 2022-11-24 21:29 UTC
Error in `preview.lua:234`:
```lua
Error executing lua callback: .../site/pack/packer/opt/glance.nvim/lua/glance/preview.lua:234: Column value outside range
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	.../site/pack/packer/opt/glance.nvim/lua/glance/preview.lua:234: in function 'update'
	...vim/site/pack/packer/opt/glance.nvim/lua/glance/init.lua:243: in function 'update_preview'
	...vim/site/pack/packer/opt/glance.nvim/lua/glance/init.lua:48: in function <...vim/site/pack/packer/opt/glance.nvim/lua/glance/init.lua:47>
```

**Comment by DNLHC** [comment] 2022-11-24 23:04
Thank you, should be fixed now.

**Closed as completed by DNLHC** 2022-11-24 23:04 UTC

**Comment by lvim-tech** [comment] 2022-11-25 00:27
Hi, @DNLHC. Maybe line 239 iv `preview.lua` `vim.cmd('norm! zz zv')` must be `vim.cmd('norm! zz')`
Then check if is folded and run command `vim.cmd('norm! zv')`

This prevents the cursor from being positioned on the second one character.

**Comment by DNLHC** [comment] 2022-11-25 11:51
From my understanding the problem occurred when `nvim_win_set_cursor` failed to set cursor on column -1
Folds shouldn't be the problem, from your logs it shows the error happened before that point.
Could you confirm the problem is fixed?

**Comment by lvim-tech** [comment] 2022-11-25 12:30
Error in `preview.lua:234` - fixed.
But with `zz zv` the cursor is positioned at second character

![1_a](https://user-images.githubusercontent.com/82431193/203986118-aae30eff-c1c0-455b-9674-dda574ebaac9.png)
![1_b](https://user-images.githubusercontent.com/82431193/203986180-fc94faf7-e49f-49df-a548-249fc0e11308.png)
![1_c](https://user-images.githubusercontent.com/82431193/203986199-49e0d67c-49fc-4d94-b2bf-30567558e54c.png)

With `zz` the cursor is positioned at first character

![2_a](https://user-images.githubusercontent.com/82431193/203986092-f9f78ef5-94d6-445e-beca-497d5ce6ceee.png)
![2_b](https://user-images.githubusercontent.com/82431193/203986291-f3a7d73d-b823-4bd0-990c-0f8c692d574a.png)
![2_c](https://user-images.githubusercontent.com/82431193/203986302-33d8cbc3-16f8-48a9-bfc7-2c92b098cecc.png)

**Comment by DNLHC** [comment] 2022-11-25 15:37
@lvim-tech I see what you mean. I'll look into it, thanks.
